export const GET_STORE_CATEGORY_SUCCESS = "GET_STORE_CATEGORY_SUCCESS";
export const GET_STORE_CATEGORY_ERROR = "GET_STORE_CATEGORY_FAILURE";
export const GET_STORE_CATEGORY_REQUEST = "GET_STORE_CATEGORY_REQUEST";
